 /*
CA, AB, AK, AL, AZ, BC, CO, CT, DC, DE, FL, GA, HI, IA, ID, IL, IN, KS, KY, LA, MA, MB, MD, ME, MI, MN, MO, MS, MT, NB, NC, ND, NE, NH, NJ, NL, NM, NS, NT, NU, NV, NY, OH, OK, ON, OR, PA, PE, QC, RI, SC, SD, SK, TN, TX, UT, VA, VT, WA, WI, WV, WY, YT
 */
export const states = {
  AB:'Alberta',
  AK:'Alaska',
  AL:'Alabama',
  AR:'Arkansas',
  AS:'American Samoa',
  AZ:'Arizona',
  BC:'British Columbia',
  CA:'California',
  CO:'Colorado',
  CT:'Connecticut',
  DC:'District of Columbia',
  DE:'Delaware',
  FL:'Florida',
  GA:'Georgia',
  HI:'Hawaii',
  IA:'Iowa',
  ID:'Idaho',
  IL:'Illinois',
  IN:'Indiana',
  KS:'Kansas',
  KY:'Kentucky',
  LA:'Louisiana',
  MA:'Massachusetts',
  MB:'Manitoba',
  MD:'Maryland',
  ME:'Maine',
  MH:'Marshall Islands',
  MI:'Michigan',
  MN:'Minnesota',
  MO:'Missouri',
  MP:'Northern Mariana Islands',
  MS:'Mississippi',
  MT:'Montana',
  NB:'New Brunswick',
  NC:'North Carolina',
  ND:'North Dakota',
  NE:'Nebraska',
  NH:'New Hampshire',
  NJ:'New Jersey',
  NL:'Newfoundland & Labrador',
  NM:'New Mexico',
  NS:'Nova Scotia',
  NT:'Northwest Territories',
  NU:'Nunavut',
  NV:'Nevada',
  NY:'New York',
  OH:'Ohio',
  OK:'Oklahoma',
  ON:'Ontario',
  OR:'Oregon',
  PA:'Pennsylvania',
  PE:'Prince Edward Island',
  PR:'Puerto Rico',
  PW:'Palau',
  QC:'Québec',
  RI:'Rhode Island',
  SC:'South Carolina',
  SD:'South Dakota',
  SK:'Saskatchewan	',
  TN:'Tennessee',
  TX:'Texas',
  UT:'Utah',
  VA:'Virginia',
  VI:'Virgin Islands',
  VT:'Vermont',
  WA:'Washington',
  WI:'Wisconsin',
  WV:'West Virginia',
  WY:'Wyoming',
  YT:'Yukon'
}
